apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend
data:
  VERSION: "1.0.0"
  ENVIRONMENT: "production"
  HOST: "0.0.0.0"
  PORT: "8000"
  HOST_DB: "mysql"
  PORT_DB: "3306"
  NAME_DB: "db_giramaster"
