apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend/configmap.yaml
  - frontend/secret.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - backend/configmap.yaml
  - backend/secret.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - celery/deployment.yaml
  - redis/configmap.yaml
  - redis/deployment.yaml
  - mysql/configmap.yaml
  - mysql/secret.yaml
  - mysql/pvc.yaml
  - mysql/deployment.yaml
  - mysql/service.yaml
  - tls-secret.yaml
  - ingress.yaml
